#! /bin/bash

g++ -g -std=c++11 -L ~/lib -I ../ -l TopTreeAnaContent72 -l TopTreeAna72 -l MLP -l TreePlayer -l TMVA -l XMLIO -I `root-config --incdir` `root-config --libs` FourTop_EventSelection_Dilepton_Run2.cc -o MACRO
